site_name: Metrô-DF

theme:
  name: material
  favicon: imagens/logoMetroDF.png
  logo: imagens/logoMetroDF.png
  palette:
    primary: green
  language: pt

docs_dir: docs/

nav: 
  - Sobre o projeto: index.md
  - Planejamento: Planejamento/planejamento.md
  - Pré-rastreabilidade: 
      - Rich Picture: Pre-Rastreabilidade/RichPicture.md
  - Elicitação de requisitos: 
      - Brainstorming: Elicitacao/brainstorming.md
      - Introspecção: Elicitacao/introspeccao.md
      - Observação Participativa: Elicitacao/observacao.md
      - Personas: Elicitacao/personas.md
      - Storyboard: Elicitacao/storyboard.md
      - Resultados: Elicitacao/resultados.md
  - Priorização de requisitos: 
      - First Things First: Priorizacao/ftf.md
      - MoSCoW:  Priorizacao/moscow.md
  - Modelagem:
      - Léxico: Modelagem/lexico.md
      - Especificação Suplementar: Modelagem/especificacao.md
      - Casos de uso: Modelagem/casodeuso.md
      - Cenários: Modelagem/cenarios.md
      - Backlog do Produto: Modelagem/backlog.md
      - Histórias de Usuário: Modelagem/historias.md
      - NFR Framework: Modelagem/nfr.md
  - Análise:
    - Verificação:
      - MoSCoW: Analise/moscow.md
      - Cenários: Analise/cenarios.md
      - Historias de usuário: Analise/historias.md
      - NFR Framework: Analise/nfr.md
      - Brainstorming: Analise/brainstorming.md
      - Introspecção: Analise/introspeccao.md
      - Observação Participativa: Analise/observacaoparticipativa.md
      - Especicifação Suplementar: Analise/especificacaosuplementar.md
      - Rich Picture: Analise/richpicture.md
      - Personas: Analise/personas.md
      - Storyboards: Analise/storyboard.md
      - Backlog do Produto: Analise/backlogdoproduto.md
      - Casos de Uso: Analise/casosdeuso.md
      - Lexicos: Analise/lexicos.md
    - Validação:
      - Prototipagem: Analise/prototipo.md
      - Informal: Analise/informal.md
  - Apresentações: 
      - Apresentação 1: Apresentacao/apresentacoes.md
      - Apresentação 2: Apresentacao/apresentacao2.md
      - Apresentação 3: Apresentacao/apresentacao3.md
      - Apresentação 4: Apresentacao/apresentacao4.md
      - Apresentação 5: Apresentacao/apresentacao5.md


